### ISSUE TITLE
Bro nice dictionary

### ISSUE THREAD

**Issue by jann-Briza** [sadarealam/Urdu_Dictionary_Test#1]
Bro nice dictionary but how can i create the database cause if i delete a lot of your database the database in corrupting and how can i create the database ty :)

**Comment by sadarealam** [comment]
Hello briza23,

sorry i am replying late .
There is database already with almost 36000 words in assets folder named local (without extension) but if you want a new database or adding some other entries then you can try any sqllite editor application .

**Comment by jann-Briza** [comment]
Thank you dude cool (y)

**Comment by jann-Briza** [comment]
bro can i ask something im kind a new to developing. what is this for:
   private final String PATH = "/data/data/test.usmaan.alam.urdudictionarytest/databases/";

**Comment by sadarealam** [comment]
this is actually path of application data folder where database reside .
This is declare here because we need to copy our dictionary from assets folder to this database folder so that SQLiteOpenHelper class can open it.

**Comment by jann-Briza** [comment]
Ohh ty Bro hehe :)

**Comment by jann-Briza** [comment]
Actually bro iam creating a Medical dictionary but instead of you will search a disease i need to create a medical dictionary that, if you search a symptom, the possible diseases will be display.

 can you help me bro :) i will appreciate a lot if you can help me hehe your a good guy :)

**Comment by sadarealam** [comment]
ya let me know what you have till date . like the database and the user interface .

**Comment by jann-Briza** [comment]
in the search bar the user will search a symptom, for example: cough, the application will display questions like: how may days is your cough, the application will give like 4 - 5 question and, after that questions the user will display list of possible illness that the symptom met. 

thats only the interface hehe :)

**Comment by jann-Briza** [comment]
YESALAM can i ask question because on Main activity the mainlist(list view) is set on invisible how can i make it visible because i tried to change it to visible but its not working. 

i need the mainlist to be visible please reply ty so mucH YESALAM :)
